### ISSUE TITLE
Ctrl-Click UNL navigation does not work

### ISSUE THREAD

**Issue by tbpassin** [boltex/leojs#93] opened 2023-12-22 04:45 UTC
I have a node in my Workbook that contains some unl strings to other nodes both in and outside of the Workbook so I can test Ctrl-click navigation.  This navigation works in Leo but not in leoJS.
```
LeoJS 0.2.6, master branch, build 91d1141
2023-12-21 23:06:09 -0500
Node.js v18.15.0, VSCode version 1.85.1
Windows 10 Home x64 (build 10.0.19045)
```

**Comment by boltex** [comment] 2023-12-22 05:09
Thanks for this issue :)

I'll mark it as Duplicate of https://github.com/boltex/leojs/issues/79

**Closed by boltex** 2023-12-22 05:09 UTC
Labels: duplicate
